config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/terms_of_use', to: 'static_pages#terms_of_use'
  get '/login', to: 'user_sessions#new', as: :login
  post '/login', to: 'user_sessions#create'
  post '/guest_login', to: 'user_sessions#guest_login'
  delete '/logout', to: 'user_sessions#destroy', as: :logout
  get '/map', to: 'photos#map'
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  get '/answer/:id', to: 'quizzes#answer', as: :answer
  resources :users, only: [:new, :create]
  resource :profile, only: [:show, :edit, :update, :destroy]
  resources :photos, only: [:new, :index, :create, :edit, :update, :destroy, :show]
  resources :diaries, only: [:new, :index, :create, :edit, :update, :destroy, :show]
  resources :lottelies, only: [:new, :index, :create, :edit, :update, :destroy]
  resources :tags do
    get 'diaries', to: 'diaries#search'
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :expenses, only: [:new, :index, :create, :edit, :update, :destroy, :show]
  resources :quizzes, only: [:new, :index, :create, :edit, :update, :destroy, :show] do
    resources :comments, only: [:create, :destroy, :update], shallow: true
  end
  resources :tasks, only: [:new, :index, :create, :edit, :update, :destroy, :show]

end

app/models/diary.rb
class Diary < ApplicationRecord
    belongs_to :user

    has_many :diary_tags, dependent: :destroy
    has_many :tags, through: :diary_tags
    validates :day, presence: true
    validates :title, presence: true
    validates :body, presence: true
    validates :user_id, presence: true

    def save_tag(sent_tags)
        current_tags = self.tags.pluck(:name) unless self.tags.nil?
        old_tags = current_tags - sent_tags
        new_tags = sent_tags - current_tags
        
        # 古いタグを削除:
        old_tags.each do |old_name|
            self.tags.delete Tag.find_by(name:old_name)
        end
        
        # 新しいタグを追加:
        new_tags.each do |new_name|
            diary_tag = Tag.find_or_create_by(name:new_name)
            self.tags << diary_tag
        end
    end
end

    

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
    before_action :set_diary, only: [:edit, :update, :destroy]
    
    def index
        @diaries = current_user.diaries.order(day: :desc)
    end
    
    def new
        @diary = Diary.new
    end

    def edit
        @tag_list = @diary.tags.pluck(:name).join('、') 
    end
    
    def create
        @diary = current_user.diaries.build(diary_params)
        sent_tags = params[:diary][:tag].split('、')
        if @diary.save
            @diary.save_tag(sent_tags)
            redirect_to diaries_path, success: t('.success')
        else
            flash.now[:danger] = t('.fail')
            render :new
        end
    end
    
    def update
        sent_tags = params[:diary][:tag].split('、')
        if @diary.update(diary_params)
            @diary.save_tag(sent_tags)
            redirect_to diaries_path, success: t('.success')
        else
            flash.now[:danger] = t('.fail')
            render :edit  
        end
    end
    
    def destroy
        @diary.destroy!
        redirect_to diaries_path, success: t('.success')
    end

    # 抽選結果
    def lottely
        @diaries = Diary.all
    end

    # タグ検索
    def search
        @tag = Tag.find(params[:tag_id])
        @diaries = @tag.diaries.where(user_id: current_user.id)
    end
    
    private
       
    def set_diary
        @diary = current_user.diaries.find(params[:id])
    end
    
    def diary_params
        params.require(:diary).permit(:day, :title, :body, :user_id)
    end
end

app/views/diaries/_diary.html.erb
<div class="col-sm-12 col-md-6 col-lg-4 mb-3">
  <div id="diary-id-<%= diary.id %>">
    <div class="border rounded overflow-hidden shadow-sm h-100">
      <div class="p-3">
        <div class="mb-1 text-body-secondary"><%= diary.day.strftime('%Y年%m月%d日') %></div></br>
        <h3 class="mb-0"><%= diary.title %></h3>
        <p class="card-text mb-auto"><%= diary.body %></p>
      </div>
      <div class="px-3 pt-3 pb-2 d-flex justify-content-between">
        <div class="btn-group">
          <% diary.tags.each do |tag| %>
            <%= link_to tag.name, tag_diaries_path(tag_id: tag.id), class: "badge text-bg-warning rounded-pill" %>
          <% end %>
        </div>
      </div>
      <div class="px-3 pb-3 d-flex justify-content-end">
        <%= link_to '編集', edit_diary_path(diary), class: 'btn btn-success mr-3' %>
          <%= link_to '削除', diary_path(diary), method: :delete, data: { confirm: t('.confirm') }, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/diaries/_form.html.erb
<%= form_with model: diary, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :day %>
      <%= f.date_field :day, class: 'form-control', type: 'date' %>
    </div></br>
  
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div></br>
  
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control' %>
    </div></br>

    <div class="form-group">
      <%= f.label :'タグ' %>
      <%= f.text_field :tag, value: @tag_list, class: 'form-control', placeholder: "、で区切って入力してください" %>
    </div></br>
  
    <div class="actions">
        <%= f.submit '保存', class: 'btn btn-info rounded-pill px-3' %>
        <%= link_to "一覧に戻る", diaries_path, class: 'btn btn-outline-secondary d-inline-flex align-items-center' %>
    </div>
<% end %>

app/views/diaries/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      <h1 class="m-5 text-center title fw-light"><%= t'.title' %></h1>
      <%= render 'form', { diary: @diary } %>  
    </div>
  </div>
</div>

app/views/diaries/index.html.erb
<% content_for(:title, t('.title')) %>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light title"><%= t'.title' %></h1></br>
        <p class="lead text-body-secondary">パークでの思い出を日記に綴ろう</br>タグを設定すると、タグをクリックすることで絞り込み検索ができます。</p></br>
      </div>
      <div>
        <%= link_to '作成', new_diary_path, class: 'btn btn-info rounded-pill px-3' %>
      </div>
    </div>
  </section>

  <div class="container pt-3">
    <div class="row">
      <div class="col-12">
        <% if @diaries.present? %>
          <div class="row">
            <%= render @diaries %>
          </div>
        <% else %>
          <p><%= 'ここに日記が掲載されます' %></p>
        <% end %>
      </div>
    </div>
  </div>



          

app/views/diaries/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="m-5 text-center title fw-light"><%= t'.title' %></h1>
      <%= render 'form', { diary: @diary } %>
    </div>
  </div>
</div>
    
    

app/views/diaries/search.html.erb
<% content_for(:title, t('.title')) %>
<section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="m-5 text-center title fw-light"><%= t'.title' %></h1></br>
          <p class="lead text-body-secondary">パークで体験した楽しかったことや感動したことを日記に綴ろう</p>
        </div>
        <div>
          <%= link_to '投稿', new_diary_path, class: 'btn btn-info rounded-pill px-3' %>
          <%= link_to '戻る', diaries_path, class: 'btn btn-outline-secondary d-inline-flex align-items-center' %>
        </div>
      </div>
</section>

<div class="container pt-3">
  <div class="row">
    <div class="col-12">
        <%= link_to tag.name, tag_diaries_path(tag_id: tag.id), class: "badge badge-warning" %>
        <%= render @diaries %>
    </div>
  </div>
</div>