config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/terms_of_use', to: 'static_pages#terms_of_use'
  get '/login', to: 'user_sessions#new', as: :login
  post '/login', to: 'user_sessions#create'
  post '/guest_login', to: 'user_sessions#guest_login'
  delete '/logout', to: 'user_sessions#destroy', as: :logout
  get '/map', to: 'photos#map'
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  get '/answer/:id', to: 'quizzes#answer', as: :answer
  resources :users, only: [:new, :create]
  resource :profile, only: [:show, :edit, :update, :destroy]
  resources :photos, only: [:new, :index, :create, :edit, :update, :destroy, :show]
  resources :diaries, only: [:new, :index, :create, :edit, :update, :destroy, :show]
  resources :lottelies, only: [:new, :index, :create, :edit, :update, :destroy]
  resources :tags do
    get 'diaries', to: 'diaries#search'
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :expenses, only: [:new, :index, :create, :edit, :update, :destroy, :show]
  resources :quizzes, only: [:new, :index, :create, :edit, :update, :destroy, :show] do
    resources :comments, only: [:create, :destroy, :update], shallow: true
  end
  resources :tasks, only: [:new, :index, :create, :edit, :update, :destroy, :show]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3 bg-body-tertiary">
    <div class="py-3 my-4">
      <span class="text-body-secondary">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href="https://docs.google.com/forms/d/e/1FAIpQLScahiKEHF7B-sHbOUxQaYG9yuhPuEHnS46ss1sGa6BjJuWpPg/viewform?usp=sf_link" class="nav-link px-2 text-body-secondary" style="color: black;" >｜　お問い合わせ　｜</a></li>
          <li class="nav-item"><a href="/terms_of_use" class="nav-link px-2 text-body-secondary" style="color: black;" >｜　利用規約　｜</a></li>
          <li class="nav-item"><a href="/privacy_policy" class="nav-link px-2 text-body-secondary" style="color: black;">｜　プライバシーポリシー　｜</a></li>
        </ul>
        <p class="text-center text-body-secondary">&copy; 2023 D PhotoMap</p>
      </span>
    </div>
</footer>

app/views/shared/_header.html.erb
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-decoration-none">
      <span class="fs-4 title">D PhotoMap</span>
    </a>
    <ul class="nav nav-pills">
      <div>
        <li class="nav-item"><i class="fas fa-images" style="color: orange;"></i></li>
        <li><%= link_to 'アルバム', photos_path, class:"nav-link", style: "color: orange;" %></li>
      </div>
      <div>
        <li class="nav-item"><i class="fas fa-map-marker-alt" style="color: red;"></i></li>
        <li><%= link_to 'マップ', '/map', class:"nav-link", style: "color: red;" %></li>
      </div>
      <div>
        <li class="nav-item"><i class="far fa-file-alt" style="color: blueviolet;"></i></li>
        <li><%= link_to '日記', diaries_path, class:"nav-link", style: "color: blueviolet;" %></li>
      </div>
      <div>
        <li class="nav-item"><i class="fas fa-dice" style="color: yellowgreen;"></i></li>
        <li><%= link_to '抽選結果', lottelies_path, class:"nav-link", style: "color: yellowgreen;" %></li>
      </div>
      <div>
        <li class="nav-item"><i class="fas fa-yen-sign" style="color: gold;"></i></li>
        <li><%= link_to '出費管理', expenses_path, class:"nav-link", style: "color: gold;" %></li>
      </div>
      <div>
        <li class="nav-item"><i class="fas fa-question-circle" style="color: rgb(228, 46, 158);"></i></li>
        <li><%= link_to 'クイズ', quizzes_path, class:"nav-link", style: "color: rgb(228, 46, 158);" %></li>
      </div>
      <div>
        <li class="nav-item"><i class="fas fa-user-plus" style="color: lightblue;"></i></li>
        <li><%= link_to 'やることリスト', tasks_path, class:"nav-link", style: "color: lightblue;" %></li>
      </div>
      <div>
        <li class="nav-item"><i class="fas fa-user-circle" style="color: blue;"></i></li>
        <li><%= link_to 'プロフィール', profile_path, class:"nav-link", style: "color: blue;" %></li>
      </div>
      <div>
        <li class="nav-item"><i class="fas fa-sign-out-alt" style="color: green;"></i></li>
        <li><%= link_to 'ログアウト', logout_path, class:"nav-link", style: "color: green;", method: :delete, data: { confirm: 'ログアウトしますか？' } %></li>
      </div>
    </ul>
</header>

app/views/shared/_header_for_guest.html.erb
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <span class="fs-4 title">D PhotoMap</span>
    </a>
    <ul class="nav nav-pills">
      <div>
        <li class="nav-itme"><i class="fas fa-home" style="color: blue;"></i></li>
        <li class="nav-item"><%= link_to 'ホーム', root_path, class: 'nav-link', style: "color: blue;" %></li>
      </div>
      <div>
        <li class="nav-itme"><i class="fas fa-sign-in-alt" style="color: rgb(228, 46, 158);"></i></li>
        <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link', style: "color: rgb(228, 46, 158);" %></li>
      </div>
      <div>
        <li class="nav-itme"><i class="fas fa-user-plus" style="color: green;"></i></li>
        <li class="nav-item"><%= link_to '新規登録', new_user_path, class: 'nav-link', style: "color: green;"%></li>
      </div>
    </ul>
</header>