config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/terms_of_use', to: 'static_pages#terms_of_use'
  get '/login', to: 'user_sessions#new', as: :login
  post '/login', to: 'user_sessions#create'
  post '/guest_login', to: 'user_sessions#guest_login'
  delete '/logout', to: 'user_sessions#destroy', as: :logout
  get '/map', to: 'photos#map'
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  get '/answer/:id', to: 'quizzes#answer', as: :answer
  resources :users, only: [:new, :create]
  resource :profile, only: [:show, :edit, :update, :destroy]
  resources :photos, only: [:new, :index, :create, :edit, :update, :destroy, :show]
  resources :diaries, only: [:new, :index, :create, :edit, :update, :destroy, :show]
  resources :lottelies, only: [:new, :index, :create, :edit, :update, :destroy]
  resources :tags do
    get 'diaries', to: 'diaries#search'
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :expenses, only: [:new, :index, :create, :edit, :update, :destroy, :show]
  resources :quizzes, only: [:new, :index, :create, :edit, :update, :destroy, :show] do
    resources :comments, only: [:create, :destroy, :update], shallow: true
  end
  resources :tasks, only: [:new, :index, :create, :edit, :update, :destroy, :show]

end

app/models/lottely.rb
class Lottely < ApplicationRecord
    belongs_to :user

    validates :day, presence: true 
    validates :facility, presence: true
    validates :time, presence: true
    validates :result, presence: true
end

app/controllers/lottelies_controller.rb
class LotteliesController < ApplicationController
  before_action :set_lottely, only: [:edit, :update, :destroy]

  def index
    @q = current_user.lottelies.ransack(params[:q])
    @lottelies = @q.result(distinct: true).includes(:user).order(day: :desc)
  end

  def new
    @lottely = Lottely.new
  end

  def edit ;end

  def create
    @lottely = current_user.lottelies.build(lottely_params)
    if @lottely.save
      redirect_to lottelies_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def update
    if @lottely.update(lottely_params)
      redirect_to lottelies_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :edit
    end
  end

  def destroy
    @lottely.destroy!
    redirect_to lottelies_path, success: t('.success')
  end

  private

  def lottely_params
    params.require(:lottely).permit(:day, :day_of_week, :facility, :time, :start_time, :result)
  end

  def set_lottely
    @lottely = current_user.lottelies.find(params[:id])
  end
end

app/views/lottelies/_form.html.erb
<%= form_with model: lottely, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :day %>
    <%= f.date_field :day, class: 'form-control', type: 'date' %>
  </div></br>
  <div class="form-group">
    <%= f.label :day_of_week %>
    <%= f.select :day_of_week, [["月曜日"],["火曜日"],["水曜日"],["木曜日"],["金曜日"],["土曜日"],["日曜日"]],{}, class: 'form-control' %>
  </div></br>
  <div class="form-group">
    <%= f.label :facility %>
    <%= f.text_field :facility, class: 'form-control' %>
  </div></br>
  <div class="form-group">
    <%= f.label :time %>
    <%= f.time_field :time, class: 'form-control', type: 'time' %>
  </div></br>
  <div class="form-group">
    <%= f.label :start_time %>
    <%= f.time_field :start_time, class: 'form-control', type: 'time' %>
  </div></br>
  <div class="form-group">
    <%= f.label :result %>
    <%= f.select :result, [["当選"],["落選"]],{}, class: 'form-control' %>
  </div></br>
  <div class="actions">
        <%= f.submit '登録', class: 'btn btn-info rounded-pill px-3' %>
        <%= link_to "一覧に戻る", lottelies_path, class: 'btn btn-outline-secondary d-inline-flex align-items-center' %>
    </div>
<% end %>

app/views/lottelies/_search.html.erb
<div class="d-flex justify-content-center">
  <%= search_form_for @q, url: url do |f| %>
    <div class="input-group mb-3">
      <div class="form-group">
        <%= f.label :day, "日にち" %>
        <%= f.search_field :day_eq, class: 'form-control', type: 'date' %>
      </div>
      <div class="form-group">
        <%= f.label :day_of_week, "曜日" %>
        <%= f.select :day_of_week_eq, [ [""],["月曜日"],["火曜日"],["水曜日"],["木曜日"],["金曜日"],["土曜日"],["日曜日"]],{}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :facility, "抽選施設" %>
        <%= f.search_field :facility_cont, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :time, "抽選時間" %>
        <%= f.search_field :time_eq, class: 'form-control', type: 'time' %>
      </div>
      <div class="form-group">
        <%= f.label :start_time, "開演時間" %>
        <%= f.search_field :start_time_eq, class: 'form-control', type: 'time' %>
      </div>
      <div class="form-group">
        <%= f.label :result, "結果" %>
        <%= f.select :result_cont, [[""],["当選"],["落選"]],{}, class: 'form-control' %> 
      </div>
      <div class="input-group-append">
        </br>
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div></br>

app/views/lottelies/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="m-5 text-center fw-light"><%= t'.title' %></h1>
      <%= render 'form', { lottely: @lottely } %>
    </div>
  </div>
</div>

app/views/lottelies/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light title"><%= t'.title' %></h1></br>
                <p class="lead text-body-secondary">検索機能を上手く活用し、</br>当選しやすい曜日や時間帯を</br>分析しよう</p></br>
            </div>
            <div>
                <%= render 'search', url: lottelies_path %>
            </div>
            <div>
                <%= link_to '入力', new_lottely_path, class: 'btn btn-info rounded-pill px-3' %>
            </div>
        </div>
    </section></br>
    <% 
       user_lottelies = current_user.lottelies
       election = user_lottelies.where(result: "当選").count
       all_lottelies = user_lottelies.where.not(result: nil).count
       winning_rate = all_lottelies > 0 ? election.to_f / all_lottelies * 100 : 0
    %>
    <h3 class="fw-bold mb-0 fs-4 title">あなたの当選確率：<%= '%.f' % winning_rate %>%</h3></br>

    <div class="table-responsive">
        <table class="table table-hover text-nowrap">
            <thead class="thead-default">
                <tr>
                    <th><%= Lottely.human_attribute_name(:day) %></th>
                    <th><%= Lottely.human_attribute_name(:day_of_week) %></th>
                    <th><%= Lottely.human_attribute_name(:facility) %></th>
                    <th><%= Lottely.human_attribute_name(:time) %></th>
                    <th><%= Lottely.human_attribute_name(:start_time) %></th>
                    <th><%= Lottely.human_attribute_name(:result) %></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @lottelies.each do |lottely| %>
                    <tr>
                        <td><%= lottely.day.strftime('%Y年%m月%d日') %></td>
                        <td><%= lottely.day_of_week %></td>
                        <td><%= lottely.facility %></td>
                        <td><%= lottely.time.strftime('%H:%M') %></td>
                        <td><%= lottely.start_time.strftime('%H:%M') %></td>
                        <td><%= lottely.result %></td>
                        <td>
                            <%= link_to '編集', edit_lottely_path(lottely), class: 'btn btn-success mr-3' %>
                            <%= link_to '削除', lottely_path(lottely), method: :delete, data: { confirm: t('.confirm') }, class: 'btn btn-danger' %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/lottelies/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="m-5 text-center title fw-light"><%= t'.title' %></h1>
      <%= render 'form', { lottely: @lottely } %>
    </div>
  </div>
</div>